# Generated by Django 3.2.5 on 2021-07-30 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=500)),
                ('school_logo', models.CharField(max_length=500)),
                ('address', models.CharField(max_length=500)),
                ('board', models.CharField(max_length=500)),
                ('co_ed_status', models.CharField(max_length=500)),
                ('ownership', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='SchoolDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_no', models.CharField(max_length=500)),
                ('webiste', models.CharField(max_length=500)),
                ('email', models.CharField(max_length=500)),
                ('lab', models.CharField(max_length=500)),
                ('year_of_establishment', models.CharField(max_length=500)),
                ('campus_size', models.CharField(max_length=500)),
                ('campus_type', models.CharField(max_length=500)),
                ('class_type', models.CharField(max_length=500)),
                ('boarding', models.CharField(max_length=500)),
                ('infrasturcure', models.CharField(max_length=500)),
                ('safty_and_security', models.CharField(max_length=500)),
                ('advance_facilities', models.CharField(max_length=500)),
                ('extra_curricular', models.CharField(max_length=500)),
                ('sports_and_fitness', models.CharField(max_length=500)),
                ('disabled_friendly', models.CharField(max_length=500)),
                ('hall_of_fame', models.CharField(max_length=99999)),
                ('gallery', models.CharField(max_length=99999)),
            ],
        ),
    ]
