# Generated by Django 3.2.5 on 2021-08-11 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0003_schooldetail_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
