# Generated by Django 3.2.5 on 2021-08-12 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0004_school_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schooldetail',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school', to='schools.school'),
        ),
    ]
