# Generated by Django 3.2.5 on 2021-08-14 06:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0006_schoolreviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolreviews',
            name='rating',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
