# Generated by Django 3.2.5 on 2021-08-14 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0007_alter_schoolreviews_rating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schoolreviews',
            options={'verbose_name_plural': 'School Reviews'},
        ),
    ]
