# Generated by Django 3.2.5 on 2021-08-20 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0009_auto_20210820_0155'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='class_offered',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
